apiVersion: v1
kind: ConfigMap
metadata:
  name: steamkube-{{ .Values.steamAppID }}
data:
  install.txt: |
    {{- include "steamkube.steamcmd.install" . | nindent 4 }}
  nginx_rcon.conf: |
    worker_processes 1;
    error_log /tmp/nginx_error.log;
    pid /tmp/nginx.pid;

    events
    {
    	worker_connections 128;
    }

    http
    {
    	client_body_temp_path /tmp/client_body;
        fastcgi_temp_path /tmp/fastcgi_temp;
        proxy_temp_path /tmp/proxy_temp;
        scgi_temp_path /tmp/scgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        server
    	{
    		listen 8080;
    		server_name localhost;
    		location /
    		{
    			root /usr/share/nginx/html;
    			index index.html index.htm;
    			error_log /tmp/nginx_error.log;
    			access_log /tmp/nginx_access.log;
    		}
    	}
    }

  server.cfg: >-
    {{- if eq .Values.steamAppID "258550" -}}
    {{- include "steamkube.server.config" . | nindent 4 }}
    {{- end }}